name: RSS to Discord

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごとに実行
  workflow_dispatch:        # 手動実行も可能

jobs:
  post_to_discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run RSS to Discord
        env:
          FEED_URL: ${{ secrets.FEED_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python rss_to_discord.py

      - name: Set up Git for commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Save last_link.txt and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add last_link.txt
          git commit -m "Update last notified link" || echo "No changes to commit"
          git push
